# Generated by Django 3.1.2 on 2020-10-06 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activitytracking',
            old_name='deleted_at',
            new_name='updated_at',
        ),
    ]
